version: "3.7"

services:
  galinhagorda-app:
    image: ghcr.io/rafaeljuniorvip/galinhagorda:latest
    networks:
      - minha_rede
    volumes:
      - galinhagorda_uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=America/Sao_Paulo
      - DB_HOST=postgres16
      - DB_PORT=5432
      - DB_NAME=galinhagorda
      - DB_USER=postgres
      - DB_PASSWORD=lkjfnsgv3u29084u7tsdkfjnv
      - JWT_SECRET=gg-prod-jwt-secret-x8f3k2m9z4p7w1q6
      - NEXT_PUBLIC_SITE_URL=https://galinhagorda.vip
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.galinhagorda.rule=Host(`galinhagorda.vip`) || Host(`www.galinhagorda.vip`)"
        - "traefik.http.routers.galinhagorda.entrypoints=websecure"
        - "traefik.http.routers.galinhagorda.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.galinhagorda.loadbalancer.server.port=3000"

volumes:
  galinhagorda_uploads:
    driver: local

networks:
  minha_rede:
    external: true
