version: "3.7"

services:
  galinhagorda-app:
    image: ghcr.io/rafaeljuniorvip/galinhagorda:latest
    networks:
      - minha_rede
    volumes:
      - galinhagorda_uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=America/Sao_Paulo
      - DB_HOST=postgres16
      - DB_PORT=5432
      - DB_NAME=galinhagorda
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_URL=https://galinhagorda.vip
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - NEXT_PUBLIC_SITE_URL=https://galinhagorda.vip
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # HTTP router (redirect to HTTPS + ACME challenge)
        - "traefik.http.routers.galinhagorda-http.rule=Host(`galinhagorda.vip`) || Host(`www.galinhagorda.vip`)"
        - "traefik.http.routers.galinhagorda-http.entrypoints=web"
        - "traefik.http.routers.galinhagorda-http.middlewares=galinhagorda-https-redirect"
        - "traefik.http.middlewares.galinhagorda-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.galinhagorda-https-redirect.redirectscheme.permanent=true"
        # HTTPS router
        - "traefik.http.routers.galinhagorda.rule=Host(`galinhagorda.vip`) || Host(`www.galinhagorda.vip`)"
        - "traefik.http.routers.galinhagorda.entrypoints=websecure"
        - "traefik.http.routers.galinhagorda.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.galinhagorda.loadbalancer.server.port=3000"

volumes:
  galinhagorda_uploads:
    driver: local

networks:
  minha_rede:
    external: true
